### ISSUE TITLE
Same table names in different postgres schemas

### ISSUE THREAD

**Issue by tr11** [bokwoon95/sqddl#4]
Hi, is there a way to force the schema name to be included on the go code generated with the `tables` command?  

Right now we're running it for each distinct schema and outputting to and appropriate subpackage, but it'd be easier if we could run it once only and have the types named as, for example, `type SCHEMA_TABLE struct ...`

Thanks!

**Comment by bokwoon95** [comment]
I could make it so that `type TABLE struct` is generated by default, but the moment there are any duplicate table names it will generate `type SCHEMA_TABLE struct` instead. Does that work for you?

**Comment by tr11** [comment]
Thank you for the quick reply! 

That works and solves our problem.  It'd be great if we could also have all the tables with the `SCHEMA_TABLE` name using some flag, but not a big deal if not.
Thanks.

**Comment by bokwoon95** [comment]
> It'd be great if we could also have all the tables with the SCHEMA_TABLE name using some flag

Yeah I think I'll do it after all, so users have the option of generating `type SCHEMA_TABLE struct` or `type TABLE struct`. The automatic `type SCHEMA_TABLE struct` behaviour will still be there because it's almost always an error if there are two generated table structs with the same name. The new flag to include the schema in the generated struct name would be called `-schema-qualified-structs`.

**Comment by bokwoon95** [comment]
> The automatic type SCHEMA_TABLE struct behaviour will still be there because it's almost always an error if there are two generated table structs with the same name

Actually maybe not, I'll just add the flag option first and if someone wants the automatic schema qualified names behaviour in the future I'll add it back in.

**Comment by bokwoon95** [comment]
I've committed it, update to [v0.4.4](https://github.com/bokwoon95/sqddl/releases/tag/v0.4.4) to get the changes.

**Comment by bokwoon95** [comment]
v0.4.4 has a bug, I forgot to set the sq struct tag for schema qualified tables. This means when sqddl parses those table structs, the table name would accidentally include the schema SCHEMA_TABLE instead of just TABLE. You should update to [v0.4.5](https://github.com/bokwoon95/sqddl/releases/tag/v0.4.5) instead 👍
