### ISSUE TITLE
Conform to golang standard generated code comment

### ISSUE THREAD

**Issue by segevd-opti** [bokwoon95/sqddl#5]
Generated files should have a comment stating that they are auto-generated. This allows automated tools to make exclusions regarding these files.

From [Go's documentation](https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source):

> To convey to humans and machine tools that code is generated, generated source should have a line that matches the following regular expression (in Go syntax):
>
> ```^// Code generated .* DO NOT EDIT\.$```
>
>This line must appear before the first non-comment, non-blank text in the file.

**Comment by bokwoon95** [comment]
Do you need these files to be detectable by automated tools? This is an exception because the code generated can be human edited. You can generate your schema structs and use it as the source of truth by adding or removing columns from it and generating the necessary SQL migrations needed to reach that state.

[https://bokwoon.neocities.org/sqddl#generate](https://bokwoon.neocities.org/sqddl#generate)

> The generate [subcommand](https://bokwoon.neocities.org/sqddl#subcommands) generates migrations needed to get from a source schema to a destination schema. The source is typically a database URL/DSN ([same as the -db flag](https://bokwoon.neocities.org/sqddl#db-flag)), while the destination is typically a Go source file containing [table structs](https://bokwoon.neocities.org/sqddl#table-structs).

**Comment by segevd-opti** [comment]
Thanks for the prompt response!

I was actually referring to the files created using `sqddl tables` and `sqddl views`.
I assumed those shouldn't be editable. Should I not use these commands directly?

**Comment by bokwoon95** [comment]
Oh the files created by `sqddl tables` are editable, yes you can generate them but you can also create them from scratch by hand. `sqddl views` can't really be edited because you can't define SQL views as struct annotations, but it's missing the generated code comment for symmetry with `sqddl tables`.

**Comment by segevd-opti** [comment]
Got it. Thanks! I think you can close the issue :)
